name: url_mapper
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.0
    - numpy
    - pandas
    - jupyter
    - scikit-learn==0.21.2
    - flask
    - nltk
    - pip:
        - langdetect
        - bs4
        - requests
        - imblearn
